In [1]:
# # 1. Import NumPy
# import numpy as np

# # 2. Creating Arrays
# np.array([1, 2, 3])  # 1D array
# np.array([[1, 2], [3, 4]])  # 2D array
# np.zeros((3, 3))  # Array of zeros
# np.ones((3, 3))  # Array of ones
# np.eye(3)  # Identity matrix
# np.full((2, 2), 7)  # Array filled with a specific value
# np.arange(0, 10, 2)  # Array with a range of values
# np.linspace(0, 1, 5)  # Array with evenly spaced values
# np.random.rand(3, 3)  # Array with random values (uniform)
# np.random.randn(3, 3)  # Array with random values (normal distribution)
# np.random.randint(0, 10, (3, 3))  # Random integers

# # 3. Inspecting Arrays
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr.shape  # Shape of the array
# arr.ndim  # Number of dimensions
# arr.size  # Number of elements
# arr.dtype  # Data type of elements

# # 4. Array Manipulation
# arr.reshape(3, 2)  # Reshape the array
# arr.flatten()  # Flatten the array to 1D
# np.transpose(arr)  # Transpose the array
# np.hstack((arr, arr))  # Horizontal stacking
# np.vstack((arr, arr))  # Vertical stacking
# np.split(arr, 2, axis=1)  # Split array along an axis

# # 5. Indexing and Slicing
# arr[1, 2]  # Access specific element
# arr[:, 1]  # Access a column
# arr[1, :]  # Access a row
# arr[0:2, 1:3]  # Slice a subarray
# arr[arr > 3]  # Conditional indexing

# # 6. Mathematical Functions
# np.add(arr, 10)  # Add scalar
# np.subtract(arr, 5)  # Subtract scalar
# np.multiply(arr, 2)  # Element-wise multiplication
# np.divide(arr, 2)  # Element-wise division
# np.power(arr, 2)  # Element-wise power
# np.sqrt(arr)  # Element-wise square root
# np.exp(arr)  # Element-wise exponential
# np.log(arr)  # Element-wise natural log
# np.abs(arr)  # Element-wise absolute value
# np.round(arr, 2)  # Round values
# np.sin(arr)  # Sine
# np.cos(arr)  # Cosine
# np.tan(arr)  # Tangent

# # 7. Aggregate Functions
# np.sum(arr)  # Sum of elements
# np.mean(arr)  # Mean of elements
# np.median(arr)  # Median of elements
# np.std(arr)  # Standard deviation
# np.var(arr)  # Variance
# np.min(arr)  # Minimum value
# np.max(arr)  # Maximum value
# np.argmin(arr)  # Index of minimum value
# np.argmax(arr)  # Index of maximum value

# # 8. Linear Algebra Functions
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[5, 6], [7, 8]])

# np.dot(A, B)  # Matrix multiplication
# A @ B  # Alternative for matrix multiplication
# np.matmul(A, B)  # Matrix multiplication
# np.cross(A, B)  # Cross product
# np.linalg.det(A)  # Determinant of a matrix
# np.linalg.inv(A)  # Inverse of a matrix
# np.linalg.eig(A)  # Eigenvalues and eigenvectors
# np.linalg.solve(A, np.array([1, 0]))  # Solve linear equations
# np.linalg.norm(A)  # Norm of a matrix or vector

# # 9. Matrix-Specific Functions
# np.trace(A)  # Trace of a matrix (sum of diagonal elements)
# np.diag(A)  # Extract diagonal elements
# np.diagflat([1, 2, 3])  # Create diagonal matrix from a list
# np.outer(np.array([1, 2]), np.array([3, 4]))  # Outer product
# np.inner(np.array([1, 2]), np.array([3, 4]))  # Inner product

# # 10. Random Sampling
# np.random.seed(42)  # Set seed for reproducibility
# np.random.choice([1, 2, 3], size=5, replace=True)  # Random choices

# # 11. Broadcasting
# arr + np.array([1, 2, 3])  # Add array to each row
# arr * np.array([[1], [2]])  # Multiply each column by corresponding scalar

# # 12. Special Functions
# np.where(arr > 3, 1, 0)  # Conditional replacement
# np.clip(arr, 0, 5)  # Clip values within a range
# np.cumsum(arr)  # Cumulative sum
# np.cumprod(arr)  # Cumulative product
# np.unique(arr)  # Find unique elements
# np.sort(arr, axis=0)  # Sort along an axis
# np.argsort(arr)  # Indices of sorted elements

# # 13. File I/O
# np.save('array.npy', arr)  # Save array to file
# np.load('array.npy')  # Load array from file
# np.savetxt('array.txt', arr, delimiter=',')  # Save array to text file
# np.loadtxt('array.txt', delimiter=',')  # Load array from text file

In [2]:

import numpy as np

In [3]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2 = np.random.randint(10, 50, size=(3, 3))
arr2

array([[31, 17, 48],
       [17, 22, 45],
       [40, 28, 19]])

In [5]:
arr3 = np.arange(1, 101, 10)
arr3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [6]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(10,)
(3, 3)
(10,)


In [7]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


In [8]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

10
9
10


In [9]:
np.reshape(arr1, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
arr4 = np.ones((5, 2), dtype=int)
print(arr4)
print(arr4.dtype)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
int64


In [13]:
arr5 = np.zeros((8, 8))
arr5

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr5[0:8:2, 0:8:2] = 1
arr5[1:8:2, 1:8:2] = 1

In [15]:
arr5

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [16]:
arr6 = np.array([1, 2, 3, 4, 5])
arr7 = np.array([5, 4, 3, 2, 1])

In [17]:
np.add(arr6, arr7)

array([6, 6, 6, 6, 6])

In [18]:
np.subtract(arr6, arr7)

array([-4, -2,  0,  2,  4])

In [19]:
np.multiply(arr6, arr7)

array([5, 8, 9, 8, 5])

In [20]:
np.divide(arr6, arr7)

array([0.2, 0.5, 1. , 2. , 5. ])

In [21]:
np.power(arr6, arr7)

array([ 1, 16, 27, 16,  5])

In [22]:
print(np.sqrt(arr6))
print(np.exp(arr6))
print(np.log(arr6))
print(np.sin(arr6))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [23]:
temp = np.sin(arr6)
print(np.round(temp, decimals=2))

[ 0.84  0.91  0.14 -0.76 -0.96]


In [24]:
arr8 = np.array([[1], [2], [3]])
arr8

array([[1],
       [2],
       [3]])

In [25]:
arr9 = np.array([1, 2, 3])
arr9

array([1, 2, 3])

In [26]:
np.add(arr8, arr9)

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [27]:
np.multiply(arr8, 10)

array([[10],
       [20],
       [30]])

In [28]:
arr10 = np.random.randint(1,10,size=(5, 5))
arr10

array([[4, 9, 5, 4, 2],
       [3, 5, 3, 3, 7],
       [8, 7, 6, 2, 2],
       [3, 5, 2, 9, 1],
       [8, 2, 1, 3, 6]])

In [29]:
temp_array = []
for i in np.nditer(arr10):
  if i > 5:
    i = 1
  elif i<= 5:
    i = 0
  temp_array.append(i)

arr11 = np.array(temp_array)
np.reshape(arr11, (5, 5))

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [30]:
arr10 = np.random.randint(1, 10, size=(5, 5))
arr11 = np.where(arr10 > 5, 1, 0)
arr11

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1]])

In [31]:
arr12 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr12

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [32]:
print(arr12[0,1])
print(arr12[2,2])
print(arr12[0])
print(arr12[:, 1])
print(arr12[0:2, 1:3])

20
90
[10 20 30]
[20 50 80]
[[20 30]
 [50 60]]


In [33]:
arr13 = np.array([5, 10, 15, 20, 25])
arr13

array([ 5, 10, 15, 20, 25])

In [34]:
np.where(arr13>12)
filter = arr13>12
arr13[filter]

array([15, 20, 25])

In [35]:
filter_1 = [1, 3, 4]
arr13[filter_1]

array([10, 20, 25])

In [36]:
arr13[::-1]

array([25, 20, 15, 10,  5])

In [37]:
arr14 = np.random.randint(1, 100, size=(5,5))

In [38]:
print(arr14)
arr14 = np.where(arr14 > 50, np.multiply(arr14, -1), arr14)


[[ 6 84 27  4 64]
 [58 87 20 59 42]
 [30 98 56 78 77]
 [46 34 99 26 64]
 [41 23 51 39 20]]


In [39]:
arr15 = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9, 10, 11, 12])
print(np.reshape(arr15, (3, 4)))
print(np.resize(arr15, (2, 6)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
arr16 = np.array([[1, 2], [3, 4]])
arr17 = np.array([[5, 6], [7, 8]])

arr18 = np.concatenate((arr16, arr17))
print(arr18)

print(np.split(arr18, 2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [41]:
arr19 = np.random.randint(1, 10, size=(2, 3, 4))
print(arr19)
print(arr19.shape)
arr20 = np.transpose(arr19, (1, 0, 2))
print(arr20)
print(arr20.shape)
arr21 = np.swapaxes(arr19, 0, 2)
print(arr21)
print(arr21.shape)

[[[2 7 3 7]
  [9 9 2 5]
  [5 1 3 6]]

 [[8 9 8 2]
  [7 8 4 6]
  [5 5 1 5]]]
(2, 3, 4)
[[[2 7 3 7]
  [8 9 8 2]]

 [[9 9 2 5]
  [7 8 4 6]]

 [[5 1 3 6]
  [5 5 1 5]]]
(3, 2, 4)
[[[2 8]
  [9 7]
  [5 5]]

 [[7 9]
  [9 8]
  [1 5]]

 [[3 8]
  [2 4]
  [3 1]]

 [[7 2]
  [5 6]
  [6 5]]]
(4, 3, 2)


In [42]:
arr22 = np.random.randint(1, 10, size=(3,3))
print(arr22)
arr22_temp = np.square(arr22[:,1:2])
arr22[:,1:2] = arr22_temp
print(arr22)
print(arr22.reshape(-1))

[[5 1 5]
 [9 3 2]
 [6 6 6]]
[[ 5  1  5]
 [ 9  9  2]
 [ 6 36  6]]
[ 5  1  5  9  9  2  6 36  6]


In [43]:
arr23 = np.random.randint(1, 50, size=(4, 5))
print(arr23)
print(np.sum(arr23))
print(np.mean(arr23))
print(np.max(arr23))
print(np.min(arr23))

[[31 24 48 38 26]
 [24 38 18 30 41]
 [17  9 28 13 49]
 [45 40 45 20 14]]
598
29.9
49
9


In [44]:
print(np.cumsum(arr23, axis=0))
print(np.cumsum(arr23, axis=1))

[[ 31  24  48  38  26]
 [ 55  62  66  68  67]
 [ 72  71  94  81 116]
 [117 111 139 101 130]]
[[ 31  55 103 141 167]
 [ 24  62  80 110 151]
 [ 17  26  54  67 116]
 [ 45  85 130 150 164]]


In [45]:
print(np.std(arr23))
print(np.var(arr23))
print(np.argmax(arr23))

12.197950647547318
148.79000000000002
14


In [46]:
arr24 = np.random.randint(10, 100, size=(6, 6))
print(arr24)



[[77 18 67 19 44 24]
 [68 97 46 23 37 81]
 [18 77 62 49 58 45]
 [14 90 51 57 30 32]
 [46 52 83 18 51 32]
 [83 63 71 53 76 13]]


In [47]:
arr25 = np.cumsum(arr24, axis=1)
np.where(arr25 > 300, 300, arr25)

array([[ 77,  95, 162, 181, 225, 249],
       [ 68, 165, 211, 234, 271, 300],
       [ 18,  95, 157, 206, 264, 300],
       [ 14, 104, 155, 212, 242, 274],
       [ 46,  98, 181, 199, 250, 282],
       [ 83, 146, 217, 270, 300, 300]])

In [48]:
arr26 = np.array([1, 2, 3])
arr27 = np.array([4, 5, 6])

np.concatenate((arr26, arr27))

array([1, 2, 3, 4, 5, 6])

In [49]:
arr28 = np.array([[1, 2], [3, 4]])
arr29 = np.array([[5, 6]])

print(arr28)
print(arr28.shape)
print(arr29)
print(arr29.shape)
print("")

print(np.concatenate((arr28, arr29.reshape(2, 1)), axis=1))
print("")
print("")
print(np.concatenate((arr28, arr29), axis=0))

[[1 2]
 [3 4]]
(2, 2)
[[5 6]]
(1, 2)

[[1 2 5]
 [3 4 6]]


[[1 2]
 [3 4]
 [5 6]]


In [50]:
print(np.vstack((arr28, arr29)))
print(np.hstack((arr28, arr29.reshape(2, 1))))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [51]:
arr30 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.split(arr30, 2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [52]:
print(np.split(arr30, [4, 8]))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10])]


In [53]:
arr31 = np.random.randint(1, 20, size=(2, 3, 3))
arr32, arr33 = np.array_split(arr31, 2, axis=0)

print(arr31)
print("")
print("===============")
print(arr32)
print("===============")
print(arr32.shape)
print("")
print("===============")
print(arr33)
print("===============")
print(arr33.shape)



[[[14 19  5]
  [19 14 13]
  [10 18  7]]

 [[10 14 10]
  [ 6  2  4]
  [10 16  6]]]

[[[14 19  5]
  [19 14 13]
  [10 18  7]]]
(1, 3, 3)

[[[10 14 10]
  [ 6  2  4]
  [10 16  6]]]
(1, 3, 3)


In [54]:
np.concatenate((arr32, arr33), axis=1)

array([[[14, 19,  5],
        [19, 14, 13],
        [10, 18,  7],
        [10, 14, 10],
        [ 6,  2,  4],
        [10, 16,  6]]])

In [55]:
# item 1 - matrix multiplication

A = np.array([[1,2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print("==========")
print(B)
print("===========")
print(np.dot(A, B))
print("===========")
print(A@B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [56]:
# item 2 - linear equations

A = np.array([[2, 1], [1, 3]])
B = np.array([5, 7])

print(np.linalg.solve(A, B))


[1.6 1.8]


In [57]:
# item 3 - Eigenvalues and Eigenvectors

C = np.array([[4, -2], [1, 1]])
print(np.linalg.eig(C))


EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]]))


In [58]:
# item 4 - Determinants and Inverse

print(np.linalg.det(A))
print("==============")
print(np.linalg.inv(A))
print("==============")
print(A@(np.linalg.inv(A)))

5.000000000000001
[[ 0.6 -0.2]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [59]:
# item 5

D = np.random.rand(3,3)
print(D)
print("=============")
print(np.linalg.eig(D))
print("=============")

B = np.array([1, 2, 3])
print(B)
print("=============")
print(np.linalg.solve(D, B))


[[0.80506017 0.76228318 0.33471024]
 [0.64543776 0.80893816 0.97809876]
 [0.9468458  0.07826056 0.69925032]]
EigResult(eigenvalues=array([1.99461318+0.j        , 0.15931774+0.48313994j,
       0.15931774-0.48313994j]), eigenvectors=array([[-0.56756056+0.j        , -0.34633989+0.3704249j ,
        -0.34633989-0.3704249j ],
       [-0.6853451 +0.j        , -0.22221272-0.53330537j,
        -0.22221272+0.53330537j],
       [-0.4562643 +0.j        ,  0.63956311+0.j        ,
         0.63956311-0.j        ]]))
[1 2 3]
[ 1.74330132 -1.44775091  2.0917606 ]


In [60]:
# Advanced Numpy - Broadcasting